### PR TITLE
Command configuration and Scope increase

### PR DESCRIPTION
**Pull request by EclipseKnight**
Implemented the ability to enable and disable commands in the configuration and increased the scope of the config to the entire project.

### CODE REVIEW

**Comment by EclipseKnight** [comment]
Additionally added the ability to enable and disable the entrance, sign, and channel servers

**Comment by Evotushon** [comment]
This seems like a good implementation but why disable those servers at all

**Comment by EclipseKnight** [comment]
For my case, I'm working on setting up individual servers to increase redundancy and reduce downtime. Having the ability to have each server standalone allows for more possibilities down the road.

**Comment by sekaiwish** [comment]
In future we could consider creating a global `Server` type then just extend `SignServer`, `EntranceServer` etc. off that which might be more or less convenient. Still have to test this implementation myself. Not sure what the downgrades in `go.sum` are about though?

**Pull request merged**
